services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:7000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://user:user@db:27017/nodejs-express-db
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: on-failure
    command: >
      sh -c "npm start"

  db:
    image: mongo:6.0
    ports:
      - "1234:27017"
    env_file:
      - .env.db
    volumes:
      - ./mongo_db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

